# Generated by Django 5.2.17 on 2026-10-05 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileUserTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temporal_level', models.CharField(choices=[('FREE', 'Free'), ('ALUMNO_PLUS_TEMPORAL', 'Alumno con Plus temporal'), ('PLUS', 'Plus de pago'), ('PRO', 'Pro de pago')], default='FREE', help_text='Nivel de acceso temporal hasta la integración con Equipos 0 y 5', max_length=25)),
                ('current_streak', models.PositiveIntegerField(default=0, help_text='Días consecutivos completando el cupo diario')),
                ('last_streak_date', models.DateField(blank=True, help_text='Última fecha en la que completó el cupo para calcular la racha', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='training_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
