# Generated by Django 5.2.17 on 2026-10-06 16:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileusertraining',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profileusertraining',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profileusertraining',
            name='temporal_level',
            field=models.CharField(choices=[('FREE', 'Free'), ('ALUMNO_PLUS_TEMPORAL', 'Alumno con Plus temporal'), ('PLUS', 'Plus de pago'), ('PRO', 'Pro de pago')], default='FREE', help_text='Nivel de acceso temporal hasta la integración con Equipos 0 y 5', max_length=50),
        ),
    ]
